blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/unknowIfGuestInDream/c-language-learning/blob/main/README.md
    about: Please check the documentation before opening an issue
